### ISSUE TITLE
快速点击新增节点按钮会抛出undefined异常

### ISSUE THREAD

**Issue by Tryndamere9** [hellowuxin/mindmap#11]

**Comment by hellowuxin** [comment]
1. 现在只有在【新增节点按钮】可见时，点击按钮才会生效
2. 但是因为新增节点后，元素发生移动，如果鼠标仍在元素上，依然会使按钮显现出来，这时，快速点击节点按钮会抛出undefined
3. 抛出undefined异常的原因应该是，多次节点新增的动画发生冲突
4. 本想使多次点击这个操作不存在（通过按钮不可见使点击无效），但是因为第2点，导致多次点击在特别的情况下仍然会发生
5. 暂未想到好的解决方法

**Comment by hellowuxin** [comment]
> 2. 但是因为新增节点后，元素发生移动，如果鼠标仍在元素上，依然会使按钮显现出来，这时，快速点击节点按钮会抛出undefined

新的版本1.6.2，将mouseover修改为mouseenter解决了第2点。
使用户不能快速点击新增按钮，规范用户行为

**Comment by Longzhiwu2015** [comment]
使用new的新数组代替旧的children，可以避免这个异常，我现在就是改了这个，可以正常使用了
