### ISSUE TITLE
关于新建节点删除问题

### ISSUE THREAD

**Issue by xudagongzi** [hellowuxin/mindmap#13]
大佬您好，新建节点后如果把文字删除，这个节点的区域就会很小很不明显，再想删除这个节点，不容易选中。
建议节点文字删除并确定后，自动把这个节点也删了，或者给节点选中区域设置个最小宽度
另外可以提pr吗

**Comment by hellowuxin** [comment]
可以提pr

**Comment by hellowuxin** [comment]
1.9.0 版本：现在节点有最小宽度和高度
