### ISSUE TITLE
节点拖拽切换节点位置

### ISSUE THREAD

**Issue by qdwds** [hellowuxin/mindmap#16]
在使用过程中，拖拽到其他节点上切换的时候，发现有很多一部分几率会失败。希望可以增加拖拽到节点上后hover效果提示
![{D9C229A6-EF18-4F61-B837-5853E88E5D46} png](https://user-images.githubusercontent.com/52602678/85005317-30789200-b18b-11ea-9f86-65c2f4cbddeb.jpg)

**Comment by hellowuxin** [comment]
其实是有实现hover提示的，你可以在这个网址试试https://mindnode.5xin.xyz/
我也遇到过没有hover提示的状况，暂时还不知道原因

**Comment by qdwds** [comment]
> 其实是有实现hover提示的，你可以在这个网址试试https://mindnode.5xin.xyz/
> 我也遇到过没有hover提示的状况，暂时还不知道原因

网上可以啊  不知道为啥我的项目不显示，
`<mindmap v-model="data" 
	:nodeClick="false" 
	:showUndo="false"
	:showNodeAdd="false"
	:fitView="false"
></mindmap>`
