### ISSUE TITLE
允许节点折叠

### ISSUE THREAD

**Issue by Cat7373** [hellowuxin/mindmap#19]
这分两种情况：
1. 上来给现成的大量数据，这时可允许用户折叠以隐藏某个节点的子节点
2. 上来给少量数据，折叠时可通过事件，从后端异步加载数据并添加为子节点

**Comment by hellowuxin** [comment]
1.10.x版本，可通过设置<code>_children</code>来折叠节点，如
```JSON
{ 
  "name":"安装",
  "_children": [ { "name": "折叠节点" } ]
}
```

**Comment by hellowuxin** [comment]
关于异步加载数据，如有需要，就另开一个issue说明吧。

**Comment by Cat7373** [comment]
现在可以把节点设置为折叠，并将其展开了，如果能再折叠回来就更好了🎉

**Comment by hellowuxin** [comment]
> 现在可以把节点设置为折叠，并将其展开了，如果能再折叠回来就更好了🎉

右键

**Comment by Cat7373** [comment]
其实 emmm，现在用鼠标好像没法移动画布和缩放了，触摸板没受影响

**Comment by hellowuxin** [comment]
> 其实 emmm，现在用鼠标好像没法移动画布和缩放了，触摸板没受影响

交互逻辑修改过，放在readme了
鼠标：space+左键移动、右键菜单、ctrl+滚轮缩放、左键选中(待做)
触控板：双指滚动移动、双指菜单、双指捏合缩放、单指选中(待做)

**Comment by Cat7373** [comment]
感觉这样用户体验不佳，而且在我这里是 Ctrl + 左键可以移动，而不是 Space
