### ISSUE TITLE
刷新页面后会出现这个样子。。。挤成一团

### ISSUE THREAD

**Issue by liyinchigithub** [hellowuxin/mindmap#4]
![image](https://user-images.githubusercontent.com/19643260/79070360-ed6fed80-7d07-11ea-8fa8-5e0470f2e06c.png)

**Comment by hellowuxin** [comment]
具体说明怎么复现这个bug，不然我无从下手

**Comment by liyinchigithub** [comment]
可能是我vue全局样式把组件样式覆盖了 。。
