### ISSUE TITLE
双击节点内容后光标的位置如何控制呢

### ISSUE THREAD

**Issue by Ritusan** [hellowuxin/mindmap#8]
大佬，我想请教一下，目前双击节点内容之后鼠标的光标是在开头的位置，可以外部进行可配置的吗，就是我想双击的时候光标的位置在内容的后面出现

**Comment by hellowuxin** [comment]
有时间会优化一下这个的

**Comment by hellowuxin** [comment]
在新的版本1.4.2中，优化了节点编辑体验：
- 单击【蓝色节点】会选中文本框所有内容
- 双击【节点】会选中点击的单词
- ...

这样子应该可以了

**Comment by Ritusan** [comment]
> 在新的版本1.4.2中，优化了节点编辑体验：
> 
> * 单击【蓝色节点】会选中文本框所有内容
> * 双击【节点】会选中点击的单词
> * ...
> 
> 这样子应该可以了

**Comment by Ritusan** [comment]
我npm install了一下发现还是1.41的版本呀

**Comment by Ritusan** [comment]
我在大佬线上的demo看了一下，目前单击的时候，按键盘的删除键可以删除当前节点，单击完之后再点击一次可以选中节点的内容进行内容的删除或编辑，但是直接双击节点的话，节点内容是中文的时候选不到所有的文字，大佬有时间可以看一下吗

**Comment by hellowuxin** [comment]
- npm update
- 双击的时候的确是选不到所有的文字，目前的特性就是这样，双击【节点】只选中点击的词

**Comment by Ritusan** [comment]
npm update 之后package.json里依赖的还是1.41的版本呀

**Comment by hellowuxin** [comment]
- 这个包在npm上最新的版本是1.4.2，这是没有问题的
- 建议你自己寻找一下更新不成功的原因

**Comment by Ritusan** [comment]
我把package.json里对应的依赖删了之后重新安装就好了，多谢大佬

**Comment by Ritusan** [comment]
大佬有博客吗，我去膜拜一下

**Comment by hellowuxin** [comment]
没有...
